/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: yc                                                    *
* Dimensions:  85 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmyc;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorsyc[] = {
  0x000000, 0xFFFFFF
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Palyc = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _acyc[] = {
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XX______, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XX___XXX, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  XXXXXXXX, XXXXXXXX, X_______, ___XXXXX, XX__XX_X, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  XXXXXXXX, XXXXXXXX, ________, ________, XX__XXXX, XXXXX___, _XXXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  XXXXXXXX, XXXXXX__, ________, ________, _____XXX, XXXXXXX_, __XXXXXX, XXXXXXXX, XXXX____, ________, ________,
  XXXXXXXX, XXXX____, ________, ________, _____XXX, XX__XXXX, XX_XXXXX, XXXXXXXX, XXX_____, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, ________, __XXXXXX, XX_XXXXX, XXXXXXXX, XX______, ________, ________,
  XXXXXXXX, X_______, ________, ________, __XX___X, X_______, _____XXX, XXXXXXX_, ________, ________, ________,
  XXXXXXXX, ________, ________, _____XXX, XXXXXXXX, XXXXXXX_, ________, _XXXX___, ________, ________, ________,
  XXXXXXX_, ________, ________, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ___X____, ________, ________, ________,
  XXXXXX__, ________, ________, _XXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________,
  XXXXX___, ________, _______X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXX____, ________, _______X, XXXXXX_X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXX____, ________, ________, ________,
  XXXX____, ________, ________, XXXXX__X, XXXX__XX, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________, ________,
  XXX_____, ________, ________, XXXXX__X, XXX__XXX, XXXXXXXX, XXXXXXXX, XXXXXX__, XXXXXXXX, XXXXX___, ________,
  XX______, ________, ________, XXXXX_XX, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXXXX, ________,
  XX______, ________, ________, XXXXX__X, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XXXXXXX, XXXXXXXX, X_______,
  XX______, ________, _______X, XXXXX__X, XX___XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_XXXXXX, XXXXXXXX, XXX_____,
  X_______, ________, ______XX, XXXXX__X, XX___XXX, XXXXXXXX, XXXXXXXX, __XXXXXX, X__XXXXX, XXXXXXXX, XXX_____,
  ________, ________, _____XXX, XXXXX__X, XX____XX, XXXXXXXX, XXXXXXXX, __XXXXXX, XX__XXXX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXX_X, XXX_XXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXX__XXX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXX_X, XXXX__XX, XXXXX___, __XXXXXX, __XXXXXX, XXXX_XXX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXX_X, XXXXXXXX, XXXX___X, X__XXXXX, X_XXXXXX, XXXX_XXX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXX_XXX, _X_XXXXX, __XXXXXX, XXXX__XX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XXXXXXX, X_XXXXXX, XXXXX_XX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, _XXXXXXX, __XXXXXX, XXXXX_XX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXX_XX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXX_XX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXX_XX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, __XXXXXX, XXXXX_XX, XXXXXXXX, XXXXX___,
  ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, ___XXXXX, XXXXX_XX, XXXXXXXX, XXXX____,
  ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XX____XX, XXXXXXX_, ___X_XXX, XXXXX_XX, XXXXXXXX, XXX_____,
  ________, ________, _____XXX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXX_, _____XXX, XXXXX_XX, XXXXXXXX, XXX_____,
  ________, ________, ______XX, XXXXXXX_, XXXXX_XX, XXXXX___, __XXXXXX, ____XXXX, XXXX__XX, XXXXXXXX, XXX_____,
  ________, ________, ______XX, XXXXXXX_, XXXX__XX, XXXXXX__, __XXXXXX, ___XXXXX, XXX___XX, XXXXXXXX, XXX_____,
  ________, ________, _______X, XXXXXX__, XXX_XXXX, XXXXXXXX, XXXXXXX_, __XXXXXX, XX___XXX, XXXXXXXX, XXX_____,
  ________, ________, _______X, XXXXXX__, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXXXX, XX______,
  ________, ________, _______X, XXXXXX__, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ___XXXXX, XXXXXXXX, X_______,
  X_______, ________, _______X, XXXXXX__, XXX__XXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXX_, ________,
  X_______, ________, ________, XXXXX___, XXX_XXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXXX__, ________,
  X_______, ________, ________, XXXXX___, XXX___XX, XXXXXXXX, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXXX___, ________,
  XX______, ________, ________, XXXXX___, XXX____X, XXXXXXXX, XXXXXXXX, XXXXX___, XXXXXXXX, XX______, ________,
  XX______, ________, ________, XXXXX___, XXXX___X, XXXXXXXX, XXXXXXXX, XXXXX___, ________, ________, ________,
  XXX_____, ________, ________, _XXXXX__, XXXX___X, XXXXXXXX, XXXXXXXX, XXX_____, ________, ________, ________,
  XXXX____, ________, ________, __XXXX__, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________, ________, ________,
  XXXX____, ________, ________, ___XXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ___X____, ________, ________, ________,
  XXXXX___, ________, ________, ____XXXX, XXXXXXXX, XXXXXXXX, XXXXXX__, _XXXXX__, ________, ________, ________,
  XXXXXX__, ________, ________, ______XX, XXXXXXXX, XXXXXXXX, XX_____X, XXXXXXXX, ________, ________, ________,
  XXXXXXX_, ________, ________, _______X, XXXXXXXX, XXXXXX__, ______XX, XXXXXXXX, X_______, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, _______X, XX__XXXX, XXXXXXXX, XX______, ________, ________,
  XXXXXXXX, ________, ________, ________, ________, ___X__XX, XX_XXXXX, XXXXXXXX, XXX_____, ________, ________,
  XXXXXXXX, XX______, ________, ________, _____XXX, _____XXX, X__XXXXX, XXXXXXXX, XXXX____, ________, ________,
  XXXXXXXX, XXX_____, ________, ________, _____XXX, _____XXX, __XXXXXX, XXXXXXXX, XXXXX___, ________, ________,
  XXXXXXXX, XXXXX___, ________, ________, _______X, XXX_____, _XXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  XXXXXXXX, XXXXXXX_, ________, ________, XX______, _______X, XXXXXXXX, XXXXXXXX, XXXXXX__, ________, ________,
  XXXXXXXX, XXXXXXXX, X_______, ______XX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXX_, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXX____, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, ________, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________,
  XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, XXXXXXXX, X_______, ________
};

GUI_CONST_STORAGE GUI_BITMAP bmyc = {
  85, // xSize
  64, // ySize
  11, // BytesPerLine
  1, // BitsPerPixel
  _acyc,  // Pointer to picture data (indices)
  &_Palyc   // Pointer to palette
};

/*************************** End of file ****************************/
